<?php

declare(strict_types=1);

namespace App\OpenApi\Schemas;

use OpenApi\Attributes as OA;

#[OA\Schema(schema: 'Currency', required: ['code', 'name', 'symbol', 'minor_units'], properties: [new OA\Property(property: 'code', type: 'string'), new OA\Property(property: 'name', type: 'string'), new OA\Property(property: 'symbol', type: 'string'), new OA\Property(property: 'minor_units', type: 'integer')], type: 'object')]
#[OA\Schema(schema: 'Ledger', required: ['id', 'title', 'currency_code', 'currency', 'member_count', 'pet_count'], properties: [new OA\Property(property: 'id', type: 'integer'), new OA\Property(property: 'title', type: 'string'), new OA\Property(property: 'currency_code', type: 'string'), new OA\Property(property: 'currency', ref: '#/components/schemas/Currency'), new OA\Property(property: 'group_id', type: 'integer', nullable: true), new OA\Property(property: 'sync_group_pets', type: 'boolean'), new OA\Property(property: 'archived_at', type: 'string', format: 'date-time', nullable: true), new OA\Property(property: 'created_by_user_id', type: 'integer'), new OA\Property(property: 'member_count', type: 'integer'), new OA\Property(property: 'pet_count', type: 'integer')], type: 'object')]
#[OA\Schema(schema: 'LedgerMember', required: ['user_id', 'name', 'start_at'], properties: [new OA\Property(property: 'user_id', type: 'integer'), new OA\Property(property: 'name', type: 'string', nullable: true), new OA\Property(property: 'start_at', type: 'string', format: 'date-time')], type: 'object')]
#[OA\Schema(schema: 'LedgerPet', required: ['id', 'name', 'can_view_profile', 'sources', 'income_minor', 'expense_minor', 'net_activity_minor'], properties: [new OA\Property(property: 'id', type: 'integer'), new OA\Property(property: 'name', type: 'string'), new OA\Property(property: 'photo_url', type: 'string', nullable: true), new OA\Property(property: 'can_view_profile', type: 'boolean'), new OA\Property(property: 'sources', type: 'array', items: new OA\Items(type: 'string')), new OA\Property(property: 'income_minor', type: 'integer', format: 'int64'), new OA\Property(property: 'expense_minor', type: 'integer', format: 'int64'), new OA\Property(property: 'net_activity_minor', type: 'integer', format: 'int64')], type: 'object')]
#[OA\Schema(schema: 'LedgerAccount', required: ['id', 'name'], properties: [new OA\Property(property: 'id', type: 'integer'), new OA\Property(property: 'name', type: 'string'), new OA\Property(property: 'archived_at', type: 'string', format: 'date-time', nullable: true), new OA\Property(property: 'income_minor', type: 'integer', format: 'int64'), new OA\Property(property: 'expense_minor', type: 'integer', format: 'int64'), new OA\Property(property: 'net_activity_minor', type: 'integer', format: 'int64')], type: 'object')]
#[OA\Schema(schema: 'LedgerCategory', required: ['id', 'name', 'applies_to'], properties: [new OA\Property(property: 'id', type: 'integer'), new OA\Property(property: 'name', type: 'string'), new OA\Property(property: 'applies_to', type: 'string', enum: ['income', 'expense', 'both']), new OA\Property(property: 'archived_at', type: 'string', format: 'date-time', nullable: true)], type: 'object')]
#[OA\Schema(schema: 'LedgerTransactionPet', required: ['name', 'name_snapshot'], properties: [new OA\Property(property: 'id', type: 'integer', nullable: true), new OA\Property(property: 'name', type: 'string'), new OA\Property(property: 'name_snapshot', type: 'string')], type: 'object')]
#[OA\Schema(schema: 'LedgerTransaction', required: ['id', 'ledger_id', 'account_id', 'type', 'amount_minor', 'amount', 'occurred_on', 'pets', 'has_receipt'], properties: [new OA\Property(property: 'id', type: 'integer'), new OA\Property(property: 'ledger_id', type: 'integer'), new OA\Property(property: 'account_id', type: 'integer'), new OA\Property(property: 'account_name', type: 'string'), new OA\Property(property: 'category_id', type: 'integer', nullable: true), new OA\Property(property: 'category_name', type: 'string', nullable: true), new OA\Property(property: 'type', type: 'string', enum: ['income', 'expense']), new OA\Property(property: 'amount_minor', type: 'integer', format: 'int64'), new OA\Property(property: 'amount', type: 'string'), new OA\Property(property: 'occurred_on', type: 'string', format: 'date'), new OA\Property(property: 'description', type: 'string', nullable: true), new OA\Property(property: 'pets', type: 'array', items: new OA\Items(ref: '#/components/schemas/LedgerTransactionPet')), new OA\Property(property: 'has_receipt', type: 'boolean')], type: 'object')]
#[OA\Schema(schema: 'LedgerTransactionPage', required: ['items', 'current_page', 'last_page', 'per_page', 'total'], properties: [new OA\Property(property: 'items', type: 'array', items: new OA\Items(ref: '#/components/schemas/LedgerTransaction')), new OA\Property(property: 'current_page', type: 'integer'), new OA\Property(property: 'last_page', type: 'integer'), new OA\Property(property: 'per_page', type: 'integer'), new OA\Property(property: 'total', type: 'integer')], type: 'object')]
#[OA\Schema(schema: 'FinanceExpenseInput', required: ['ledger_id', 'account_id', 'amount'], properties: [new OA\Property(property: 'ledger_id', type: 'integer'), new OA\Property(property: 'account_id', type: 'integer'), new OA\Property(property: 'category_id', type: 'integer', nullable: true), new OA\Property(property: 'amount', type: 'string'), new OA\Property(property: 'description', type: 'string', nullable: true)], type: 'object')]
#[OA\Schema(schema: 'LedgerTransactionInput', required: ['account_id', 'type', 'amount', 'occurred_on'], properties: [new OA\Property(property: 'account_id', type: 'integer'), new OA\Property(property: 'category_id', type: 'integer', nullable: true), new OA\Property(property: 'type', type: 'string', enum: ['income', 'expense']), new OA\Property(property: 'amount', type: 'string'), new OA\Property(property: 'occurred_on', type: 'string', format: 'date'), new OA\Property(property: 'description', type: 'string', nullable: true), new OA\Property(property: 'pet_ids', type: 'array', items: new OA\Items(type: 'integer'))], type: 'object')]
#[OA\Schema(schema: 'LedgerInvitation', required: ['id', 'token', 'status', 'expires_at', 'invitation_url'], properties: [new OA\Property(property: 'id', type: 'integer'), new OA\Property(property: 'token', type: 'string'), new OA\Property(property: 'status', type: 'string'), new OA\Property(property: 'expires_at', type: 'string', format: 'date-time'), new OA\Property(property: 'invitation_url', type: 'string')], type: 'object')]
#[OA\Schema(schema: 'LedgerInvitationCreated', required: ['invitation', 'invitation_url'], properties: [new OA\Property(property: 'invitation', ref: '#/components/schemas/LedgerInvitation'), new OA\Property(property: 'invitation_url', type: 'string')], type: 'object')]
#[OA\Schema(schema: 'LedgerDashboard', required: ['current_month', 'previous_month', 'accounts', 'recent_transactions', 'spending_by_category', 'spending_by_pet', 'income_by_category', 'monthly_trend'], properties: [new OA\Property(property: 'current_month', type: 'object'), new OA\Property(property: 'previous_month', type: 'object'), new OA\Property(property: 'accounts', type: 'array', items: new OA\Items(ref: '#/components/schemas/LedgerAccount')), new OA\Property(property: 'recent_transactions', type: 'array', items: new OA\Items(ref: '#/components/schemas/LedgerTransaction')), new OA\Property(property: 'spending_by_category', type: 'array', items: new OA\Items(type: 'object')), new OA\Property(property: 'spending_by_pet', type: 'array', items: new OA\Items(type: 'object')), new OA\Property(property: 'income_by_category', type: 'array', items: new OA\Items(type: 'object')), new OA\Property(property: 'monthly_trend', type: 'array', items: new OA\Items(type: 'object'))], type: 'object')]
class FinanceSchemas {}
