<?php

declare(strict_types=1);

namespace App\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Get(path: '/api/currencies', summary: 'List enabled finance currencies', tags: ['Finances'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'Enabled currencies', content: new OA\JsonContent(properties: [new OA\Property(property: 'data', type: 'array', items: new OA\Items(ref: '#/components/schemas/Currency'))]))])]
#[OA\Get(path: '/api/ledgers', summary: 'List accessible Ledgers', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'archived', in: 'query', schema: new OA\Schema(type: 'boolean'))], responses: [new OA\Response(response: 200, description: 'Ledgers', content: new OA\JsonContent(properties: [new OA\Property(property: 'data', type: 'array', items: new OA\Items(ref: '#/components/schemas/Ledger'))]))])]
#[OA\Post(path: '/api/ledgers', summary: 'Create a Ledger with starter configuration', tags: ['Finances'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['title', 'currency_code'], properties: [new OA\Property(property: 'title', type: 'string'), new OA\Property(property: 'currency_code', type: 'string')])), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(properties: [new OA\Property(property: 'data', ref: '#/components/schemas/Ledger')]))])]
#[OA\Get(path: '/api/ledgers/{ledger}', summary: 'Show a Ledger', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Ledger', content: new OA\JsonContent(properties: [new OA\Property(property: 'data', ref: '#/components/schemas/Ledger')]))])]
#[OA\Put(path: '/api/ledgers/{ledger}', summary: 'Update a Ledger', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(properties: [new OA\Property(property: 'title', type: 'string'), new OA\Property(property: 'currency_code', type: 'string')])), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(properties: [new OA\Property(property: 'data', ref: '#/components/schemas/Ledger')]))])]
#[OA\Post(path: '/api/ledgers/{ledger}/archive', summary: 'Archive a Ledger', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Archived')])]
#[OA\Post(path: '/api/ledgers/{ledger}/restore', summary: 'Restore a Ledger', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Restored', content: new OA\JsonContent(properties: [new OA\Property(property: 'data', ref: '#/components/schemas/Ledger')]))])]
#[OA\Delete(path: '/api/ledgers/{ledger}', summary: 'Delete an empty Ledger', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 204, description: 'Deleted')])]
#[OA\Get(path: '/api/ledgers/{ledger}/members', summary: 'List Ledger members', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Members', content: new OA\JsonContent(properties: [new OA\Property(property: 'data', type: 'array', items: new OA\Items(ref: '#/components/schemas/LedgerMember'))]))])]
#[OA\Delete(path: '/api/ledgers/{ledger}/members/{user}', summary: 'Remove a Ledger member', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'user', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 204, description: 'Removed')])]
#[OA\Post(path: '/api/ledgers/{ledger}/leave', summary: 'Leave a Ledger', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 204, description: 'Left')])]
#[OA\Get(path: '/api/ledgers/{ledger}/pets', summary: 'List pets available to a Ledger', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Pets', content: new OA\JsonContent(properties: [new OA\Property(property: 'data', type: 'array', items: new OA\Items(ref: '#/components/schemas/LedgerPet'))]))])]
#[OA\Post(path: '/api/ledgers/{ledger}/pets/{pet}', summary: 'Add a pet to a Ledger', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'pet', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 201, description: 'Added')])]
#[OA\Delete(path: '/api/ledgers/{ledger}/pets/{pet}', summary: 'Remove manual pet availability', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'pet', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 204, description: 'Removed')])]
#[OA\Post(path: '/api/ledgers/{ledger}/group-link', summary: 'Link a Group to a Ledger', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['group_id'], properties: [new OA\Property(property: 'group_id', type: 'integer'), new OA\Property(property: 'import_pets', type: 'boolean'), new OA\Property(property: 'sync_group_pets', type: 'boolean')])), responses: [new OA\Response(response: 200, description: 'Linked')])]
#[OA\Delete(path: '/api/ledgers/{ledger}/group-link', summary: 'Detach a Group from a Ledger', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 204, description: 'Detached')])]
#[OA\Get(path: '/api/ledgers/{ledger}/accounts', summary: 'List Ledger accounts and activity totals', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Accounts', content: new OA\JsonContent(properties: [new OA\Property(property: 'data', type: 'array', items: new OA\Items(ref: '#/components/schemas/LedgerAccount'))]))])]
#[OA\Post(path: '/api/ledgers/{ledger}/accounts', summary: 'Create a Ledger account', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['name'], properties: [new OA\Property(property: 'name', type: 'string')])), responses: [new OA\Response(response: 201, description: 'Created')])]
#[OA\Put(path: '/api/ledgers/{ledger}/accounts/{account}', summary: 'Rename a Ledger account', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'account', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['name'], properties: [new OA\Property(property: 'name', type: 'string')])), responses: [new OA\Response(response: 200, description: 'Updated')])]
#[OA\Post(path: '/api/ledgers/{ledger}/accounts/{account}/archive', summary: 'Toggle Ledger account archive state', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'account', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Updated')])]
#[OA\Get(path: '/api/ledgers/{ledger}/categories', summary: 'List Ledger categories', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Categories', content: new OA\JsonContent(properties: [new OA\Property(property: 'data', type: 'array', items: new OA\Items(ref: '#/components/schemas/LedgerCategory'))]))])]
#[OA\Post(path: '/api/ledgers/{ledger}/categories', summary: 'Create a Ledger category', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(required: ['name', 'applies_to'], properties: [new OA\Property(property: 'name', type: 'string'), new OA\Property(property: 'applies_to', type: 'string', enum: ['income', 'expense', 'both'])])), responses: [new OA\Response(response: 201, description: 'Created')])]
#[OA\Put(path: '/api/ledgers/{ledger}/categories/{category}', summary: 'Update a Ledger category', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'category', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(properties: [new OA\Property(property: 'name', type: 'string'), new OA\Property(property: 'applies_to', type: 'string', enum: ['income', 'expense', 'both'])])), responses: [new OA\Response(response: 200, description: 'Updated')])]
#[OA\Post(path: '/api/ledgers/{ledger}/categories/{category}/archive', summary: 'Toggle Ledger category archive state', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'category', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Updated')])]
#[OA\Get(path: '/api/ledgers/{ledger}/transactions', summary: 'List and filter Ledger transactions', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'date_from', in: 'query', schema: new OA\Schema(type: 'string', format: 'date')), new OA\Parameter(name: 'date_to', in: 'query', schema: new OA\Schema(type: 'string', format: 'date')), new OA\Parameter(name: 'type', in: 'query', schema: new OA\Schema(type: 'string', enum: ['income', 'expense'])), new OA\Parameter(name: 'account_id', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'category_id', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'pet_id', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'creator_id', in: 'query', schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'search', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Transactions', content: new OA\JsonContent(properties: [new OA\Property(property: 'data', ref: '#/components/schemas/LedgerTransactionPage')]))])]
#[OA\Post(path: '/api/ledgers/{ledger}/transactions', summary: 'Create a Ledger transaction', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(ref: '#/components/schemas/LedgerTransactionInput')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(properties: [new OA\Property(property: 'data', ref: '#/components/schemas/LedgerTransaction')]))])]
#[OA\Get(path: '/api/ledgers/{ledger}/transactions/{transaction}', summary: 'Show a Ledger transaction', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'transaction', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Transaction')])]
#[OA\Put(path: '/api/ledgers/{ledger}/transactions/{transaction}', summary: 'Update a Ledger transaction', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'transaction', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(ref: '#/components/schemas/LedgerTransactionInput')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(properties: [new OA\Property(property: 'data', ref: '#/components/schemas/LedgerTransaction')]))])]
#[OA\Delete(path: '/api/ledgers/{ledger}/transactions/{transaction}', summary: 'Soft-delete a Ledger transaction', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'transaction', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 204, description: 'Deleted')])]
#[OA\Post(path: '/api/ledgers/{ledger}/transactions/{transaction}/receipt', summary: 'Upload or replace a private receipt', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'transaction', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(required: true, content: new OA\MediaType(mediaType: 'multipart/form-data', schema: new OA\Schema(required: ['receipt'], properties: [new OA\Property(property: 'receipt', type: 'string', format: 'binary')]))), responses: [new OA\Response(response: 201, description: 'Uploaded')])]
#[OA\Delete(path: '/api/ledgers/{ledger}/transactions/{transaction}/receipt', summary: 'Delete a private receipt', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'transaction', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 204, description: 'Deleted')])]
#[OA\Get(path: '/api/ledgers/{ledger}/transactions/{transaction}/receipt', summary: 'Download a private receipt', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'transaction', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Receipt bytes')])]
#[OA\Get(path: '/api/ledgers/{ledger}/dashboard', summary: 'Get Ledger dashboard aggregates', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Dashboard', content: new OA\JsonContent(properties: [new OA\Property(property: 'data', ref: '#/components/schemas/LedgerDashboard')]))])]
#[OA\Get(path: '/api/pets/{pet}/finance-transactions', summary: 'List pet-linked transactions visible through the viewer’s Ledgers', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'pet', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Transactions', content: new OA\JsonContent(properties: [new OA\Property(property: 'data', ref: '#/components/schemas/LedgerTransactionPage')]))])]
#[OA\Post(path: '/api/ledgers/{ledger}/invitations', summary: 'Create a seven-day Ledger invitation', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(properties: [new OA\Property(property: 'data', ref: '#/components/schemas/LedgerInvitationCreated')]))])]
#[OA\Get(path: '/api/ledgers/{ledger}/invitations', summary: 'List pending Ledger invitations', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Invitations', content: new OA\JsonContent(properties: [new OA\Property(property: 'data', type: 'array', items: new OA\Items(ref: '#/components/schemas/LedgerInvitation'))]))])]
#[OA\Delete(path: '/api/ledgers/{ledger}/invitations/{invitation}', summary: 'Revoke a Ledger invitation', tags: ['Finances'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'ledger', in: 'path', required: true, schema: new OA\Schema(type: 'integer')), new OA\Parameter(name: 'invitation', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 204, description: 'Revoked')])]
class FinanceOperations {}
