<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Seed approved cities for a curated set of countries.
     *
     * Note: This project stores the country as ISO 3166-1 alpha-2 code in `cities.country`.
     * There is no separate `countries` table.
     */
    public function run(): void
    {
        $countryCities = [
            'IN' => [
                ['en' => 'Mumbai'],
                ['en' => 'Delhi'],
                ['en' => 'Bengaluru'],
                ['en' => 'Chennai'],
                ['en' => 'Hyderabad'],
                ['en' => 'Kolkata'],
                ['en' => 'Pune'],
                ['en' => 'Ahmedabad'],
                ['en' => 'Jaipur'],
            ],
            'CN' => [
                ['en' => 'Shanghai'],
                ['en' => 'Beijing'],
                ['en' => 'Guangzhou'],
                ['en' => 'Shenzhen'],
                ['en' => 'Chongqing'],
                ['en' => 'Tianjin'],
                ['en' => 'Wuhan'],
                ['en' => 'Chengdu'],
                ['en' => 'Hangzhou'],
            ],
            'US' => [
                ['en' => 'New York'],
                ['en' => 'Los Angeles'],
                ['en' => 'Chicago'],
                ['en' => 'Houston'],
                ['en' => 'Phoenix'],
                ['en' => 'Philadelphia'],
                ['en' => 'San Antonio'],
                ['en' => 'San Diego'],
                ['en' => 'Dallas'],
            ],
            'ID' => [
                ['en' => 'Jakarta'],
                ['en' => 'Surabaya'],
                ['en' => 'Bandung'],
                ['en' => 'Medan'],
                ['en' => 'Bekasi'],
                ['en' => 'Depok'],
                ['en' => 'Tangerang'],
                ['en' => 'Semarang'],
            ],
            'PK' => [
                ['en' => 'Karachi'],
                ['en' => 'Lahore'],
                ['en' => 'Faisalabad'],
                ['en' => 'Rawalpindi'],
                ['en' => 'Multan'],
                ['en' => 'Gujranwala'],
                ['en' => 'Peshawar'],
                ['en' => 'Quetta'],
            ],
            'NG' => [
                ['en' => 'Lagos'],
                ['en' => 'Abuja'],
                ['en' => 'Ibadan'],
                ['en' => 'Benin City'],
                ['en' => 'Port Harcourt'],
                ['en' => 'Onitsha'],
                ['en' => 'Enugu'],
                ['en' => 'Aba'],
            ],
            'BR' => [
                ['en' => 'São Paulo'],
                ['en' => 'Rio de Janeiro'],
                ['en' => 'Belo Horizonte'],
                ['en' => 'Brasília'],
                ['en' => 'Salvador'],
                ['en' => 'Fortaleza'],
                ['en' => 'Recife'],
                ['en' => 'Porto Alegre'],
            ],
            'BD' => [
                ['en' => 'Dhaka'],
                ['en' => 'Chittagong'],
                ['en' => 'Gazipur'],
                ['en' => 'Narayanganj'],
                ['en' => 'Khulna'],
                ['en' => 'Sylhet'],
                ['en' => 'Rajshahi'],
            ],
            'RU' => [
                ['en' => 'Moscow', 'ru' => 'Москва', 'vi' => 'Mát-xcơ-va'],
                ['en' => 'Saint Petersburg', 'ru' => 'Санкт-Петербург', 'vi' => 'Xanh Pê-téc-bua'],
                ['en' => 'Novosibirsk', 'ru' => 'Новосибирск', 'vi' => 'Nô-vô-xi-biếc'],
                ['en' => 'Yekaterinburg', 'ru' => 'Екатеринбург'],
                ['en' => 'Kazan', 'ru' => 'Казань'],
                ['en' => 'Nizhny Novgorod', 'ru' => 'Нижний Новгород'],
                ['en' => 'Chelyabinsk', 'ru' => 'Челябинск'],
                ['en' => 'Samara', 'ru' => 'Самара'],
                ['en' => 'Omsk', 'ru' => 'Омск'],
                ['en' => 'Rostov-on-Don', 'ru' => 'Ростов-на-Дону'],
                ['en' => 'Ufa', 'ru' => 'Уфа'],
                ['en' => 'Krasnoyarsk', 'ru' => 'Красноярск'],
                ['en' => 'Perm', 'ru' => 'Пермь'],
                ['en' => 'Voronezh', 'ru' => 'Воронеж'],
                ['en' => 'Volgograd', 'ru' => 'Волгоград'],
                ['en' => 'Saratov', 'ru' => 'Саратов'],
                ['en' => 'Krasnodar', 'ru' => 'Краснодар'],
                ['en' => 'Tolyatti', 'ru' => 'Тольятти'],
                ['en' => 'Izhevsk', 'ru' => 'Ижевск'],
                ['en' => 'Barnaul', 'ru' => 'Барнаул'],
            ],
            'ET' => [
                ['en' => 'Addis Ababa'],
                ['en' => 'Dire Dawa'],
                ['en' => 'Mekelle'],
                ['en' => 'Gondar'],
                ['en' => 'Hawassa'],
                ['en' => 'Bahir Dar'],
            ],
            'MX' => [
                ['en' => 'Mexico City'],
                ['en' => 'Guadalajara'],
                ['en' => 'Monterrey'],
                ['en' => 'Puebla'],
                ['en' => 'Toluca'],
                ['en' => 'Tijuana'],
                ['en' => 'León'],
                ['en' => 'Querétaro'],
            ],
            'JP' => [
                ['en' => 'Tokyo'],
                ['en' => 'Yokohama'],
                ['en' => 'Osaka'],
                ['en' => 'Nagoya'],
                ['en' => 'Sapporo'],
                ['en' => 'Fukuoka'],
                ['en' => 'Kobe'],
                ['en' => 'Kyoto'],
            ],
            'EG' => [
                ['en' => 'Cairo'],
                ['en' => 'Giza'],
                ['en' => 'Alexandria'],
                ['en' => 'Shubra El-Kheima'],
                ['en' => 'Port Said'],
                ['en' => 'Suez'],
                ['en' => 'Mansoura'],
            ],
            'PH' => [
                ['en' => 'Quezon City'],
                ['en' => 'Manila'],
                ['en' => 'Davao City'],
                ['en' => 'Cebu City'],
                ['en' => 'Caloocan'],
                ['en' => 'Makati'],
                ['en' => 'Pasig'],
            ],
            'CD' => [
                ['en' => 'Kinshasa'],
                ['en' => 'Lubumbashi'],
                ['en' => 'Mbuji-Mayi'],
                ['en' => 'Kisangani'],
                ['en' => 'Kananga'],
                ['en' => 'Kolwezi'],
            ],
            'VN' => [
                ['en' => 'Ho Chi Minh City', 'vi' => 'Thành phố Hồ Chí Minh', 'ru' => 'Хошимин'],
                ['en' => 'Hanoi', 'vi' => 'Hà Nội', 'ru' => 'Ханой'],
                ['en' => 'Da Nang', 'vi' => 'Đà Nẵng', 'ru' => 'Дананг'],
                ['en' => 'Can Tho', 'vi' => 'Cần Thơ', 'ru' => 'Кантхо'],
                ['en' => 'Hai Phong', 'vi' => 'Hải Phòng', 'ru' => 'Хайфон'],
                ['en' => 'Bien Hoa', 'vi' => 'Biên Hòa', 'ru' => 'Бьенхоа'],
                ['en' => 'Hue', 'vi' => 'Huế', 'ru' => 'Хюэ'],
                ['en' => 'Nha Trang', 'vi' => 'Nha Trang', 'ru' => 'Нячанг'],
                ['en' => 'Vung Tau', 'vi' => 'Vũng Tàu', 'ru' => 'Вунгтау'],
            ],
            'IR' => [
                ['en' => 'Tehran'],
                ['en' => 'Mashhad'],
                ['en' => 'Isfahan'],
                ['en' => 'Karaj'],
                ['en' => 'Shiraz'],
                ['en' => 'Tabriz'],
                ['en' => 'Qom'],
            ],
            'TR' => [
                ['en' => 'Istanbul'],
                ['en' => 'Ankara'],
                ['en' => 'Izmir'],
                ['en' => 'Bursa'],
                ['en' => 'Antalya'],
                ['en' => 'Adana'],
                ['en' => 'Konya'],
            ],
            'DE' => [
                ['en' => 'Berlin'],
                ['en' => 'Hamburg'],
                ['en' => 'Munich'],
                ['en' => 'Cologne'],
                ['en' => 'Frankfurt'],
                ['en' => 'Stuttgart'],
                ['en' => 'Düsseldorf'],
            ],
            'TH' => [
                ['en' => 'Bangkok'],
                ['en' => 'Nonthaburi'],
                ['en' => 'Samut Prakan'],
                ['en' => 'Chiang Mai'],
                ['en' => 'Hat Yai'],
                ['en' => 'Phuket'],
            ],
            'TZ' => [
                ['en' => 'Dar es Salaam'],
                ['en' => 'Mwanza'],
                ['en' => 'Arusha'],
                ['en' => 'Dodoma'],
                ['en' => 'Mbeya'],
                ['en' => 'Morogoro'],
            ],
            'GB' => [
                ['en' => 'London'],
                ['en' => 'Birmingham'],
                ['en' => 'Manchester'],
                ['en' => 'Leeds'],
                ['en' => 'Liverpool'],
                ['en' => 'Bristol'],
                ['en' => 'Sheffield'],
            ],
            'FR' => [
                ['en' => 'Paris'],
                ['en' => 'Marseille'],
                ['en' => 'Lyon'],
                ['en' => 'Toulouse'],
                ['en' => 'Nice'],
                ['en' => 'Nantes'],
                ['en' => 'Strasbourg'],
            ],
            'ZA' => [
                ['en' => 'Johannesburg'],
                ['en' => 'Cape Town'],
                ['en' => 'Durban'],
                ['en' => 'Pretoria'],
                ['en' => 'Soweto'],
                ['en' => 'Bloemfontein'],
            ],
            'IT' => [
                ['en' => 'Rome'],
                ['en' => 'Milan'],
                ['en' => 'Naples'],
                ['en' => 'Turin'],
                ['en' => 'Palermo'],
                ['en' => 'Bologna'],
                ['en' => 'Florence'],
            ],
            'KE' => [
                ['en' => 'Nairobi'],
                ['en' => 'Mombasa'],
                ['en' => 'Kisumu'],
                ['en' => 'Nakuru'],
                ['en' => 'Eldoret'],
                ['en' => 'Thika'],
            ],
            'MM' => [
                ['en' => 'Yangon'],
                ['en' => 'Mandalay'],
                ['en' => 'Naypyidaw'],
                ['en' => 'Mawlamyine'],
                ['en' => 'Bago'],
            ],
            'CO' => [
                ['en' => 'Bogotá'],
                ['en' => 'Medellín'],
                ['en' => 'Cali'],
                ['en' => 'Barranquilla'],
                ['en' => 'Cartagena'],
                ['en' => 'Bucaramanga'],
            ],
            'KR' => [
                ['en' => 'Seoul'],
                ['en' => 'Busan'],
                ['en' => 'Incheon'],
                ['en' => 'Daegu'],
                ['en' => 'Daejeon'],
                ['en' => 'Gwangju'],
                ['en' => 'Suwon'],
            ],
            'SD' => [
                ['en' => 'Khartoum'],
                ['en' => 'Omdurman'],
                ['en' => 'Port Sudan'],
                ['en' => 'Kassala'],
                ['en' => 'El Obeid'],
            ],
            'UG' => [
                ['en' => 'Kampala'],
                ['en' => 'Wakiso'],
                ['en' => 'Mukono'],
                ['en' => 'Gulu'],
                ['en' => 'Mbarara'],
            ],
            'ES' => [
                ['en' => 'Madrid'],
                ['en' => 'Barcelona'],
                ['en' => 'Valencia'],
                ['en' => 'Seville'],
                ['en' => 'Zaragoza'],
                ['en' => 'Málaga'],
            ],
            'DZ' => [
                ['en' => 'Algiers'],
                ['en' => 'Oran'],
                ['en' => 'Constantine'],
                ['en' => 'Annaba'],
                ['en' => 'Batna'],
            ],
            'IQ' => [
                ['en' => 'Baghdad'],
                ['en' => 'Basra'],
                ['en' => 'Mosul'],
                ['en' => 'Erbil'],
                ['en' => 'Najaf'],
                ['en' => 'Karbala'],
            ],
            'AR' => [
                ['en' => 'Buenos Aires'],
                ['en' => 'Córdoba'],
                ['en' => 'Rosario'],
                ['en' => 'Mendoza'],
                ['en' => 'La Plata'],
            ],
            'AF' => [
                ['en' => 'Kabul'],
                ['en' => 'Kandahar'],
                ['en' => 'Herat'],
                ['en' => 'Mazar-i-Sharif'],
                ['en' => 'Jalalabad'],
            ],
            'YE' => [
                ['en' => 'Sanaa'],
                ['en' => 'Aden'],
                ['en' => 'Taiz'],
                ['en' => 'Al Hudaydah'],
                ['en' => 'Ibb'],
            ],
            'CA' => [
                ['en' => 'Toronto'],
                ['en' => 'Montreal'],
                ['en' => 'Vancouver'],
                ['en' => 'Calgary'],
                ['en' => 'Edmonton'],
                ['en' => 'Ottawa'],
            ],
            'AO' => [
                ['en' => 'Luanda'],
                ['en' => 'Huambo'],
                ['en' => 'Lobito'],
                ['en' => 'Benguela'],
                ['en' => 'Lubango'],
            ],
            'UA' => [
                ['en' => 'Kyiv'],
                ['en' => 'Kharkiv'],
                ['en' => 'Odesa'],
                ['en' => 'Dnipro'],
                ['en' => 'Lviv'],
                ['en' => 'Zaporizhzhia'],
                ['en' => 'Kryvyi Rih'],
                ['en' => 'Mykolaiv'],
                ['en' => 'Mariupol'],
                ['en' => 'Vinnytsia'],
                ['en' => 'Chernihiv'],
                ['en' => 'Poltava'],
                ['en' => 'Cherkasy'],
                ['en' => 'Sumy'],
                ['en' => 'Zhytomyr'],
                ['en' => 'Kropyvnytskyi'],
                ['en' => 'Rivne'],
                ['en' => 'Ternopil'],
                ['en' => 'Ivano-Frankivsk'],
                ['en' => 'Chernivtsi'],
                ['en' => 'Khmelnytskyi'],
                ['en' => 'Kramatorsk'],
                ['en' => 'Melitopol'],
                ['en' => 'Berdyansk'],
                ['en' => 'Sloviansk'],
            ],
            'MA' => [
                ['en' => 'Casablanca'],
                ['en' => 'Rabat'],
                ['en' => 'Fes'],
                ['en' => 'Marrakesh'],
                ['en' => 'Tangier'],
                ['en' => 'Agadir'],
            ],
            'PL' => [
                ['en' => 'Warsaw'],
                ['en' => 'Kraków'],
                ['en' => 'Łódź'],
                ['en' => 'Wrocław'],
                ['en' => 'Poznań'],
                ['en' => 'Gdańsk'],
            ],
            'UZ' => [
                ['en' => 'Tashkent'],
                ['en' => 'Samarkand'],
                ['en' => 'Bukhara'],
                ['en' => 'Namangan'],
                ['en' => 'Andijan'],
            ],
            'MY' => [
                ['en' => 'Kuala Lumpur'],
                ['en' => 'Petaling Jaya'],
                ['en' => 'Subang Jaya'],
                ['en' => 'Johor Bahru'],
                ['en' => 'Penang'],
            ],
            'MZ' => [
                ['en' => 'Maputo'],
                ['en' => 'Matola'],
                ['en' => 'Beira'],
                ['en' => 'Nampula'],
                ['en' => 'Chimoio'],
            ],
            'GH' => [
                ['en' => 'Accra'],
                ['en' => 'Kumasi'],
                ['en' => 'Tamale'],
                ['en' => 'Takoradi'],
                ['en' => 'Cape Coast'],
            ],
            'PE' => [
                ['en' => 'Lima'],
                ['en' => 'Arequipa'],
                ['en' => 'Trujillo'],
                ['en' => 'Chiclayo'],
                ['en' => 'Piura'],
            ],
            'SA' => [
                ['en' => 'Riyadh'],
                ['en' => 'Jeddah'],
                ['en' => 'Mecca'],
                ['en' => 'Medina'],
                ['en' => 'Dammam'],
                ['en' => 'Khobar'],
            ],
            'MG' => [
                ['en' => 'Antananarivo'],
                ['en' => 'Toamasina'],
                ['en' => 'Antsirabe'],
                ['en' => 'Fianarantsoa'],
                ['en' => 'Mahajanga'],
            ],
            'CI' => [
                ['en' => 'Abidjan'],
                ['en' => 'Bouaké'],
                ['en' => 'Daloa'],
                ['en' => 'San-Pédro'],
                ['en' => 'Yamoussoukro'],
            ],
        ];

        foreach ($countryCities as $country => $cities) {
            $country = strtoupper($country);

            foreach ($cities as $cityData) {
                $enName = $cityData['en'];
                $translations = $cityData;

                // Check if city exists by name in English or slug (safer)
                $city = City::where('country', $country)
                    ->where('name->en', $enName)
                    ->first();

                if (! $city) {
                    City::create([
                        'name' => $translations,
                        'country' => $country,
                        'approved_at' => now(),
                        'created_by' => null,
                        'description' => null,
                    ]);

                    continue;
                }

                // Update translations for existing cities
                $city->update([
                    'name' => $translations,
                ]);

                if ($city->approved_at === null) {
                    $city->approve();
                }
            }
        }
    }
}
